### ISSUE TITLE
Сообщение об инициализации

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/ipc_chip_info#4]
При выполнении инициализации сенсора приложение может "подвисать" на 15-20 секунд. Что-бы пользовательне нервничал, неплохо было-бы выводить какое-то сообщение, мол, подождите N секунд.

**Comment by widgetii** [comment]
There is a bug in HiSilicon based kernel: it won't work without loaded ko modules from SDK. So currently I think of sole workaround to measure `ioctl` execution time and exit early in error message.

Implemented in master
